#!/usr/bin/env bash

################################################################################
# Workstation
################################################################################

if [[ -r "${HOME}/Sites/personal/workstation/shell/bash/init.sh" ]]; then

    # shellcheck disable=SC1090
    source "${HOME}/Sites/personal/workstation/shell/bash/init.sh"

fi