#!/usr/bin/env bash

################################################################################
# Workstation
################################################################################

INSTALLATION_ENV="${HOME}/.config/workstation/installation.env"

if [[ -r "${INSTALLATION_ENV}" ]]; then

    # shellcheck disable=SC1090
    source "${INSTALLATION_ENV}"

fi

if [[ -n "${PRODUCT_ROOT:-}" ]] \
    && [[ -r "${PRODUCT_ROOT}/shell/bash/init.sh" ]]; then

    # shellcheck disable=SC1090
    source "${PRODUCT_ROOT}/shell/bash/init.sh"

fi